"""
Traefik configuration generation for SyrvisCore.

Generates static and dynamic configuration files for Traefik reverse proxy.
"""

import os


def generate_traefik_static_config() -> str:
    """
    Generate Traefik static configuration (traefik.yml).

    Static configuration defines:
    - API/Dashboard settings
    - Entry points (ports 80, 443)
    - Providers (Docker, file-based)
    - Logging configuration
    - Let's Encrypt certificate resolver

    Returns:
        YAML content as string
    """
    acme_email = os.getenv("ACME_EMAIL", "admin@example.com")

    config = f"""# Traefik Static Configuration
# Generated by SyrvisCore

api:
  dashboard: true
  insecure: true  # Dashboard on :8080 (internal only)

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
  file:
    directory: "/config"
    watch: true

log:
  level: INFO
  filePath: "/logs/traefik.log"

accessLog:
  filePath: "/logs/access.log"

certificatesResolvers:
  letsencrypt:
    acme:
      email: {acme_email}
      storage: /acme.json
      httpChallenge:
        entryPoint: web
"""
    return config


def generate_traefik_dynamic_config() -> str:
    """
    Generate Traefik dynamic configuration (config/dynamic.yml).

    Dynamic configuration can be updated without restarting Traefik.
    Defines routing rules, services, and middleware.

    Returns:
        YAML content as string
    """
    domain = os.getenv("DOMAIN", "example.com")

    config = f"""# Traefik Dynamic Configuration
# Generated by SyrvisCore
# This file can be updated without restarting Traefik

http:
  routers:
    # Traefik Dashboard (HTTP)
    dashboard:
      rule: "Host(`traefik.{domain}`)"
      service: api@internal
      entryPoints:
        - web

    # Traefik Dashboard (HTTPS)
    dashboard-secure:
      rule: "Host(`traefik.{domain}`)"
      service: api@internal
      entryPoints:
        - websecure
      tls: {{}}
"""
    return config
