"""
Traefik configuration generation for SyrvisCore.

Generates static and dynamic configuration files for Traefik reverse proxy.
"""

import os
from typing import Dict, List, Optional


# =============================================================================
# Synology Services Configuration
# =============================================================================
# Define Synology NAS services that can be proxied through Traefik.
# Each service has a subdomain, target port, and protocol.
#
# To add a new service:
#   1. Add an entry to SYNOLOGY_SERVICES
#   2. Set the corresponding env var to enable it (e.g., SYNOLOGY_DSM_ENABLED=true)
#   3. Run 'syrvis setup' to regenerate configs

SYNOLOGY_SERVICES = {
    # Service key: (subdomain, port, protocol, description)
    # Note: DS File removed - use SMB directly to NAS IP instead
    "photos": {
        "subdomain": "photos",
        "port": 5001,
        "protocol": "https",
        "description": "Photos (Synology Photos / Photo Station)",
        "env_enabled": "SYNOLOGY_PHOTOS_ENABLED",
    },
    "dsm": {
        "subdomain": "dsm",
        "port": 5001,
        "protocol": "https",
        "description": "DSM Web Interface",
        "env_enabled": "SYNOLOGY_DSM_ENABLED",
    },
    "drive": {
        "subdomain": "drive",
        "port": 6690,
        "protocol": "https",
        "description": "Synology Drive",
        "env_enabled": "SYNOLOGY_DRIVE_ENABLED",
    },
    "audio": {
        "subdomain": "audio",
        "port": 5001,
        "protocol": "https",
        "description": "Audio Station",
        "env_enabled": "SYNOLOGY_AUDIO_ENABLED",
    },
    "video": {
        "subdomain": "video",
        "port": 5001,
        "protocol": "https",
        "description": "Video Station",
        "env_enabled": "SYNOLOGY_VIDEO_ENABLED",
    },
}


def get_enabled_synology_services() -> Dict[str, dict]:
    """Get list of enabled Synology services from environment variables."""
    enabled = {}
    for key, config in SYNOLOGY_SERVICES.items():
        env_var = config["env_enabled"]
        if os.getenv(env_var, "").lower() in ("true", "1", "yes"):
            enabled[key] = config
    return enabled


def generate_traefik_static_config() -> str:
    """
    Generate Traefik static configuration (traefik.yml).

    Static configuration defines:
    - API/Dashboard settings
    - Entry points (ports 80, 443)
    - Providers (Docker, file-based)
    - Logging configuration
    - Let's Encrypt certificate resolver

    Returns:
        YAML content as string
    """
    acme_email = os.getenv("ACME_EMAIL", "admin@example.com")

    config = f"""# Traefik Static Configuration
# Generated by SyrvisCore

api:
  dashboard: true
  insecure: true  # Dashboard on :8080 (internal only)

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: proxy
  file:
    directory: "/config"
    watch: true

log:
  level: INFO
  filePath: "/logs/traefik.log"

accessLog:
  filePath: "/logs/access.log"

certificatesResolvers:
  letsencrypt:
    acme:
      email: {acme_email}
      storage: /acme.json
      httpChallenge:
        entryPoint: web
"""
    return config


def generate_synology_routers_config(domain: str, nas_ip: str) -> str:
    """
    Generate Traefik router configuration for enabled Synology services.

    Args:
        domain: Base domain (e.g., konsume.org)
        nas_ip: IP address of the Synology NAS

    Returns:
        YAML snippet for routers section
    """
    enabled_services = get_enabled_synology_services()
    if not enabled_services:
        return ""

    lines = [
        "",
        "    # =========================================================================",
        "    # Synology NAS Services",
        "    # =========================================================================",
    ]

    for key, config in enabled_services.items():
        subdomain = config["subdomain"]
        lines.extend([
            f"",
            f"    # {config['description']} (HTTP -> HTTPS redirect)",
            f"    synology-{key}:",
            f"      rule: \"Host(`{subdomain}.{domain}`)\"",
            f"      service: synology-{key}",
            f"      entryPoints:",
            f"        - web",
            f"      middlewares:",
            f"        - https-redirect",
            f"",
            f"    # {config['description']} (HTTPS with Let's Encrypt)",
            f"    synology-{key}-secure:",
            f"      rule: \"Host(`{subdomain}.{domain}`)\"",
            f"      service: synology-{key}",
            f"      entryPoints:",
            f"        - websecure",
            f"      tls:",
            f"        certResolver: letsencrypt",
        ])

    return "\n".join(lines)


def generate_synology_services_config(nas_ip: str) -> str:
    """
    Generate Traefik service configuration for enabled Synology services.

    Args:
        nas_ip: IP address of the Synology NAS

    Returns:
        YAML snippet for services section
    """
    enabled_services = get_enabled_synology_services()
    if not enabled_services:
        return ""

    lines = [
        "",
        "  # ===========================================================================",
        "  # Synology NAS Services",
        "  # ===========================================================================",
        "  services:",
    ]

    for key, config in enabled_services.items():
        protocol = config["protocol"]
        port = config["port"]
        lines.extend([
            f"    synology-{key}:",
            f"      loadBalancer:",
            f"        servers:",
            f"          - url: \"{protocol}://{nas_ip}:{port}\"",
            f"        serversTransport: insecure-skip-verify@file",
        ])

    # Add serversTransport for self-signed certs on Synology
    lines.extend([
        "",
        "  serversTransports:",
        "    insecure-skip-verify:",
        "      insecureSkipVerify: true",
    ])

    return "\n".join(lines)


def generate_traefik_dynamic_config() -> str:
    """
    Generate Traefik dynamic configuration (config/dynamic.yml).

    Dynamic configuration can be updated without restarting Traefik.
    Defines routing rules, services, and middleware.

    Returns:
        YAML content as string
    """
    domain = os.getenv("DOMAIN", "example.com")
    nas_ip = os.getenv("NAS_IP", "")
    shim_ip = os.getenv("SHIM_IP", "")

    # For macvlan: Traefik container cannot reach NAS directly at NAS_IP.
    # It must use SHIM_IP (the macvlan shim interface) to reach the host.
    # If SHIM_IP is set, use it as the backend; otherwise fall back to NAS_IP.
    backend_ip = shim_ip if shim_ip else nas_ip

    # Generate Synology services config if backend IP is available
    synology_routers = ""
    synology_services = ""
    if backend_ip:
        synology_routers = generate_synology_routers_config(domain, backend_ip)
        synology_services = generate_synology_services_config(backend_ip)

    config = f"""# Traefik Dynamic Configuration
# Generated by SyrvisCore
# This file can be updated without restarting Traefik

http:
  routers:
    # =========================================================================
    # SyrvisCore Services
    # =========================================================================

    # Traefik Dashboard (HTTP -> HTTPS redirect)
    dashboard:
      rule: "Host(`traefik.{domain}`)"
      service: api@internal
      entryPoints:
        - web
      middlewares:
        - https-redirect

    # Traefik Dashboard (HTTPS with Let's Encrypt)
    dashboard-secure:
      rule: "Host(`traefik.{domain}`)"
      service: api@internal
      entryPoints:
        - websecure
      tls:
        certResolver: letsencrypt
{synology_routers}

  middlewares:
    # Redirect HTTP to HTTPS
    https-redirect:
      redirectScheme:
        scheme: https
        permanent: true
{synology_services}
"""
    return config
